# https://stackoverflow.com/questions/71197980/conda-environment-and-channels

name: data
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - matplotlib
  - pandas
  - seaborn
  - ipykernel
  - scikit-learn
  - netcdf4
  - cartopy
  - nbconvert
  - cmasher